### ISSUE TITLE
enchants including vanilla ones are infinite

### ISSUE THREAD

**Issue by FullMetalMaster** [tristankechlo/Tool-Leveling#2]
there needs to be a conflict to limit how many times something can be put through the upgrade table. vanilla and modded and chance can be done all the way up to another right blocks to a ridiculous degree, and also making some combinations impossible to kill somebody the only current config is in the world if there's some way to limit the amount of times you can put something in and I know this can be done in the world file but some way to disable what enchantments can be put in and what can't be modded as well would also be great

**Comment by tristankechlo** [comment]
Your issue was quite hard to read, but what I think you want is some sort of limitations to the upgrade-process?
Some sort of enchantment-blacklist(enchantments players are not allowed to level up) should already be in the config.
My plan for the next update is to add a list to the config with new enchantment caps(new maximum levels).
