### ISSUE TITLE
Add config option to change numeric display back to roman numerals 

### ISSUE THREAD

**Issue by jengendler** [tristankechlo/Tool-Leveling#4]
**Is your feature request related to a problem? Please describe.**
This mod changes Roman numerals on tiered enchantments, such as Sharpness I, Sharpness II, etc., to Western-Arabic numerals (a.k.a "regular numbers"), such as Sharpness 1, Sharpness 2, etc. I can understand why this was changed (so as to increase readability when tools are leveled to large numbers), but I strongly prefer the Roman numerals. I enjoy the mental exercise, plus they simply look nice.

**Describe the solution you'd like**
It would be great if there was a client-side config setting that allowed one to choose the numeric display as Roman numerals or "regular" numbers.

This mod is awesome, btw. :)

**Comment by tristankechlo** [comment]
Changing the number system through a config-option is not possible.
That's done with language files(which are included in resource packs).
I will however remove the translations of the first 10 levels from the mod resources, so that those will be by default the roman numbers again.
All following levels are going to stay the normal number system, if you want them to be roman numbers, you need to make a custom resource pack.
